import type {
  Article,
  Category,
  Newsletter,
  NewsletterBundle,
  Publication,
} from "@/lib/types";

export const platformStats = {
  publications: 17,
  activeNewsletters: 24,
  categories: 8,
  weeklyReaders: "420B+",
};

export const categories: Category[] = [
  {
    slug: "ekonomi",
    name: "Ekonomi & Finans",
    shortName: "Ekonomi",
    description: "Piyasalar, şirketler ve kişisel finans için bağlamı güçlü analizler.",
    color: "#d8f45f",
  },
  {
    slug: "spor",
    name: "Spor",
    shortName: "Spor",
    description: "Skorun ötesinde taktik, kültür, transfer ve performans hikâyeleri.",
    color: "#ff6a48",
  },
  {
    slug: "gastronomi",
    name: "Gastronomi",
    shortName: "Gastronomi",
    description: "Mevsimlik tarifler, mutfak kültürü ve pratik sofra fikirleri.",
    color: "#f4abc3",
  },
  {
    slug: "aile-cocuk",
    name: "Aile & Çocuk",
    shortName: "Aile & Çocuk",
    description: "Ebeveynler için güvenilir, uygulanabilir ve neşeli günlük rehberler.",
    color: "#ffd76b",
  },
  {
    slug: "iyi-yasam",
    name: "İyi Yaşam",
    shortName: "İyi Yaşam",
    description: "Sağlık, hareket ve gündelik denge için sürdürülebilir öneriler.",
    color: "#9edfc9",
  },
  {
    slug: "ev-tasarim",
    name: "Ev & Tasarım",
    shortName: "Ev & Tasarım",
    description: "Yaşam alanları, mimari ve yeni nesil tasarım kültürü.",
    color: "#ddd2bf",
  },
  {
    slug: "is-etkinlik",
    name: "İş & Etkinlik",
    shortName: "İş & Etkinlik",
    description: "Sektör buluşmaları, fuarlar, konferanslar ve iş dünyası gündemi.",
    color: "#8dcef7",
  },
  {
    slug: "kultur-trend",
    name: "Kültür & Trend",
    shortName: "Kültür & Trend",
    description: "İnternet kültürü, yaratıcı endüstriler ve yeni neslin radarındakiler.",
    color: "#b9b7ff",
  },
];

export const publications: Publication[] = [
  {
    slug: "piyasavizyon",
    name: "PiyasaVizyon",
    kicker: "Ekonominin arka planı",
    description: "Piyasa hareketlerini yalnızca rakamlarla değil, nedenleriyle okur.",
    longDescription:
      "PiyasaVizyon; para politikası, şirketler, yatırım araçları ve gündelik ekonomi arasındaki bağlantıları sade, veri odaklı bir editoryal dille açıklar.",
    categorySlug: "ekonomi",
    color: "#d8f45f",
    foreground: "#10130b",
    monogram: "PV",
    cadence: "Günde 2 yayın",
    reach: "96 bin okur",
    featured: true,
  },
  {
    slug: "direktspor",
    name: "Direktspor",
    kicker: "Skordan fazlası",
    description: "Oyunun taktiğini, ekonomisini ve tribündeki kültürünü birlikte anlatır.",
    longDescription:
      "Direktspor; futbol başta olmak üzere performans sporlarını güncel veri, saha içi analiz ve güçlü hikâye anlatımıyla takip eder.",
    categorySlug: "spor",
    color: "#ff6a48",
    foreground: "#18100d",
    monogram: "DS",
    cadence: "Her gün",
    reach: "122 bin okur",
    featured: true,
  },
  {
    slug: "kidsgourmet",
    name: "KidsGourmet",
    kicker: "Çocuklarla iyi beslenme",
    description: "Ebeveynlerin gerçek hayatına uyan beslenme ve gelişim rehberleri.",
    longDescription:
      "KidsGourmet; çocuk beslenmesini yasaklar üzerinden değil, aile sofrası, merak ve sürdürülebilir alışkanlıklar üzerinden ele alır.",
    categorySlug: "aile-cocuk",
    color: "#ffd76b",
    foreground: "#171208",
    monogram: "KG",
    cadence: "Haftada 4 yayın",
    reach: "74 bin ebeveyn",
    featured: true,
  },
  {
    slug: "tariften",
    name: "Tariften",
    kicker: "Bugün ne pişirsem?",
    description: "İyi tarifleri mevsim, zaman ve bütçe gerçekliğiyle buluşturur.",
    longDescription:
      "Tariften; test edilmiş tarifler, alışveriş listeleri ve sofraya dair küçük tekniklerle mutfaktaki karar yükünü azaltır.",
    categorySlug: "gastronomi",
    color: "#f4abc3",
    foreground: "#1a0f13",
    monogram: "TF",
    cadence: "Her gün",
    reach: "108 bin okur",
    featured: true,
  },
  {
    slug: "rejimde",
    name: "Rejimde",
    kicker: "Daha iyi hisset",
    description: "İyi yaşamı kısa vadeli hedeflerden çıkarıp gündelik bir ritme dönüştürür.",
    longDescription:
      "Rejimde; uyku, hareket, beslenme ve zihin sağlığını uzman görüşleriyle, iddiasız ama sürdürülebilir adımlara çevirir.",
    categorySlug: "iyi-yasam",
    color: "#9edfc9",
    foreground: "#0c1713",
    monogram: "RJ",
    cadence: "Haftada 5 yayın",
    reach: "84 bin okur",
  },
  {
    slug: "home-trendsetter",
    name: "Home Trendsetter",
    kicker: "Mekânın yeni hâli",
    description: "Tasarımı, trendleri ve gündelik yaşam alanlarını editoryal bir gözle seçer.",
    longDescription:
      "Home Trendsetter; iç mimari, obje, malzeme ve yaşam kültürünü global eğilimlerle yerel üretim arasında konumlandırır.",
    categorySlug: "ev-tasarim",
    color: "#ddd2bf",
    foreground: "#17140f",
    monogram: "HT",
    cadence: "Haftada 3 yayın",
    reach: "58 bin okur",
  },
  {
    slug: "sektorel-ajanda",
    name: "Sektörel Ajanda",
    kicker: "İş dünyasının takvimi",
    description: "Doğru etkinliği, doğru sektör ve doğru bağlantıyla eşleştirir.",
    longDescription:
      "Sektörel Ajanda; fuarları, zirveleri ve profesyonel buluşmaları tek takvimde toplarken öne çıkan sektör hareketlerini de yorumlar.",
    categorySlug: "is-etkinlik",
    color: "#8dcef7",
    foreground: "#0a141b",
    monogram: "SA",
    cadence: "Haftada 3 yayın",
    reach: "42 bin profesyonel",
  },
  {
    slug: "hipinup",
    name: "hipinup",
    kicker: "Şimdi ne oluyor?",
    description: "İnternetin hızını bağlam, seçki ve yaratıcı bir bakışla yavaşlatır.",
    longDescription:
      "hipinup; yükselen davranışları, internet kültürünü, yaratıcı işleri ve yeni nesil tüketim dilini gürültüden ayırır.",
    categorySlug: "kultur-trend",
    color: "#b9b7ff",
    foreground: "#100f1c",
    monogram: "HU",
    cadence: "Haftada 4 yayın",
    reach: "69 bin okur",
  },
];

export const newsletters: Newsletter[] = [
  {
    slug: "piyasa-acilisi",
    name: "Piyasa Açılışı",
    publicationSlug: "piyasavizyon",
    categorySlug: "ekonomi",
    description: "Piyasalar açılmadan önce bilmen gereken beş gelişme.",
    longDescription:
      "Gece boyunca oluşan fiyatlamayı, günün veri takvimini ve Borsa İstanbul için öne çıkan başlıkları sekiz dakikalık bir sabah okumasında toplar.",
    schedule: "Hafta içi her sabah",
    deliveryTime: "08.15",
    format: "8 dakikalık okuma",
    audience: "71 bin abone",
    accent: "#d8f45f",
    featured: true,
    topics: ["Piyasa özeti", "Veri takvimi", "Günün şirketi"],
  },
  {
    slug: "halka-arz-radari",
    name: "Halka Arz Radarı",
    publicationSlug: "piyasavizyon",
    categorySlug: "ekonomi",
    description: "Takvim, izahname ve performans verisi tek e-postada.",
    longDescription:
      "Yeni halka arzları, talep toplama takvimini ve şirketlerin temel göstergelerini karşılaştırmalı olarak sunar.",
    schedule: "Her perşembe",
    deliveryTime: "17.30",
    format: "Veri dosyası",
    audience: "38 bin abone",
    accent: "#d8f45f",
    topics: ["Takvim", "Şirket kartı", "Risk notları"],
  },
  {
    slug: "ilk-duduk",
    name: "İlk Düdük",
    publicationSlug: "direktspor",
    categorySlug: "spor",
    description: "Dünün sonucu, bugünün maçı ve oyunun tek kritik detayı.",
    longDescription:
      "Günün spor gündemini skor kalabalığından ayırır; gece oynananların anlamını ve günün izleme planını kısa bir akışta sunar.",
    schedule: "Her sabah",
    deliveryTime: "07.45",
    format: "6 dakikalık okuma",
    audience: "86 bin abone",
    accent: "#ff6a48",
    featured: true,
    topics: ["Skor özeti", "Taktik kare", "İzleme rehberi"],
  },
  {
    slug: "transfer-hatti",
    name: "Transfer Hattı",
    publicationSlug: "direktspor",
    categorySlug: "spor",
    description: "Söylenti değil; kaynak, ihtiyaç ve maliyet analizi.",
    longDescription:
      "Transfer haberlerini kulüp ihtiyacı, oyuncu profili ve finansal gerçeklikle birlikte değerlendirir.",
    schedule: "Salı ve cuma",
    deliveryTime: "18.00",
    format: "Derin analiz",
    audience: "52 bin abone",
    accent: "#ff6a48",
    topics: ["Günün transferi", "Kadro ihtiyacı", "Maliyet"],
  },
  {
    slug: "haftalik-cocuk-menusu",
    name: "Haftalık Çocuk Menüsü",
    publicationSlug: "kidsgourmet",
    categorySlug: "aile-cocuk",
    description: "Beş gün, tek alışveriş listesi, daha sakin bir hafta.",
    longDescription:
      "Okul ve ev temposuna uyarlanan beş günlük menüyü, alternatifleri ve hazırlık planıyla birlikte gönderir.",
    schedule: "Her pazar",
    deliveryTime: "10.00",
    format: "Plan + alışveriş listesi",
    audience: "49 bin abone",
    accent: "#ffd76b",
    featured: true,
    topics: ["5 günlük menü", "Alışveriş listesi", "Beslenme çantası"],
  },
  {
    slug: "ebeveyn-notu",
    name: "Ebeveyn Notu",
    publicationSlug: "kidsgourmet",
    categorySlug: "aile-cocuk",
    description: "Bir uzman görüşü, bir uygulanabilir fikir.",
    longDescription:
      "Çocuk gelişimi ve aile sofrasına dair tek bir konuyu, güvenilir kaynak ve kısa uygulama önerisiyle açıklar.",
    schedule: "Her çarşamba",
    deliveryTime: "12.30",
    format: "4 dakikalık not",
    audience: "36 bin abone",
    accent: "#ffd76b",
    topics: ["Uzman görüşü", "Evde uygulama", "Kaynak seçkisi"],
  },
  {
    slug: "aksam-ne-pisirsem",
    name: "Akşam Ne Pişirsem?",
    publicationSlug: "tariften",
    categorySlug: "gastronomi",
    description: "Mevsimlik, denenmiş ve 40 dakikanın altında tarifler.",
    longDescription:
      "Her hafta içi akşamı, zamanı ve malzemeyi gözeten bir ana tarif ile onu tamamlayan küçük bir servis fikri sunar.",
    schedule: "Hafta içi",
    deliveryTime: "16.30",
    format: "Tarif kartı",
    audience: "79 bin abone",
    accent: "#f4abc3",
    featured: true,
    topics: ["Günün tarifi", "Malzeme değişimi", "Servis fikri"],
  },
  {
    slug: "iyi-yasam-notlari",
    name: "İyi Yaşam Notları",
    publicationSlug: "rejimde",
    categorySlug: "iyi-yasam",
    description: "Haftaya daha dengeli başlamak için küçük bir rehber.",
    longDescription:
      "Uyku, hareket, beslenme ve zihin sağlığından bir başlığı bilimsel kaynağı ve uygulanabilir adımıyla ele alır.",
    schedule: "Her pazartesi",
    deliveryTime: "07.30",
    format: "5 dakikalık okuma",
    audience: "61 bin abone",
    accent: "#9edfc9",
    topics: ["Haftanın odağı", "Uzman notu", "Mini alışkanlık"],
  },
  {
    slug: "evde-gundem",
    name: "Evde Gündem",
    publicationSlug: "home-trendsetter",
    categorySlug: "ev-tasarim",
    description: "Yeni ürünler, malzemeler ve mekânlardan haftalık seçki.",
    longDescription:
      "Editörün radarına giren iç mekânları, yerel tasarımcıları ve yaşam alanlarına yön veren fikirleri haftalık bir seçkide birleştirir.",
    schedule: "Her çarşamba",
    deliveryTime: "11.00",
    format: "Görsel seçki",
    audience: "33 bin abone",
    accent: "#ddd2bf",
    topics: ["Mekân", "Obje", "Malzeme"],
  },
  {
    slug: "haftanin-etkinlikleri",
    name: "Haftanın Etkinlikleri",
    publicationSlug: "sektorel-ajanda",
    categorySlug: "is-etkinlik",
    description: "Sektörüne göre filtrelenmiş profesyonel etkinlik takvimi.",
    longDescription:
      "Türkiye ve yakın coğrafyadaki fuar, zirve ve konferansları sektör, şehir ve tarih bilgisiyle tek e-postada toplar.",
    schedule: "Her pazartesi",
    deliveryTime: "09.00",
    format: "Takvim",
    audience: "28 bin abone",
    accent: "#8dcef7",
    topics: ["Fuar", "Zirve", "Son başvuru"],
  },
  {
    slug: "trend-alarmi",
    name: "Trend Alarmı",
    publicationSlug: "hipinup",
    categorySlug: "kultur-trend",
    description: "İnternet neden bugün bunu konuşuyor?",
    longDescription:
      "Bir davranış, format veya yaratıcı iş üzerinden haftanın yükselen internet kültürü sinyalini bağlamıyla açıklar.",
    schedule: "Her salı",
    deliveryTime: "14.00",
    format: "Trend analizi",
    audience: "47 bin abone",
    accent: "#b9b7ff",
    topics: ["Sinyal", "Neden şimdi?", "Marka etkisi"],
  },
  {
    slug: "hiposta-haftalik",
    name: "Hiposta Haftalık",
    publicationSlug: "hipinup",
    categorySlug: "kultur-trend",
    description: "17 yayının en iyi fikirleri tek pazar sayısında.",
    longDescription:
      "Hip Medya editörlerinin hafta boyunca yayımladığı içeriklerden, farklı ilgi alanlarını dengeli biçimde bir araya getiren premium bir dergi seçkisi.",
    schedule: "Her pazar",
    deliveryTime: "09.30",
    format: "Dijital dergi",
    audience: "92 bin abone",
    accent: "#2444e8",
    featured: true,
    topics: ["Editör seçkisi", "Haftanın dosyası", "Kısa öneriler"],
  },
];

export const articles: Article[] = [
  {
    slug: "faiz-indirimleri-baslarken-sonbaharin-yatirim-haritasi",
    title: "Faiz indirimleri başlarken sonbaharın yatırım haritası",
    dek: "Para politikasında yeni bir dönem açılırken mevduat, borsa ve altın arasındaki denge yeniden kuruluyor.",
    publicationSlug: "piyasavizyon",
    categorySlug: "ekonomi",
    author: "Deniz Ertem",
    publishedAt: "2026-08-26T07:15:00+03:00",
    displayDate: "26 Ağustos 2026",
    readTime: "6 dk",
    premium: true,
    featured: true,
    heroImage: "https://images.unsplash.com/photo-1589561454226-796a8aa89b05?auto=format&fit=crop&w=1800&q=82",
    heroAlt: "Boğaz ve İstanbul silüeti",
    photoCredit: "Engin Yapıcı / Unsplash",
    body: [
      "Önümüzdeki üç ayda yatırımcının yalnızca getiriyi değil, vade ve likiditeyi de birlikte düşünmesi gerekecek. Faiz indiriminin yönü netleşse bile fiyatlamanın hızı her varlık sınıfında aynı olmayacak.",
      "Mevduat cephesinde nominal getiri aşağı gelirken gerçek getiri bir süre daha pozitif bölgede kalabilir. Bu, kısa vadeli nakit ihtiyacı olan yatırımcı için köprü stratejisini hâlâ anlamlı kılıyor.",
      "Hisse senetlerinde ise endeks yerine bilanço seçimi öne çıkıyor. Finansman gideri düşen, iç talep yavaşlarken ihracatla denge kurabilen şirketler yeni döneme daha avantajlı başlayacak.",
      "Altın tarafında küresel faiz patikası kadar kur oynaklığı da belirleyici. Tek seferde büyük pozisyon yerine zamana yayılan alımlar, sonbaharın belirsizliğine daha uygun bir risk profili sunuyor.",
    ],
    relatedNewsletterSlug: "piyasa-acilisi",
    tags: ["Faiz", "Yatırım", "Borsa", "Altın"],
  },
  {
    slug: "yeni-sezonun-oyunu-daha-hizli-daha-genc",
    title: "Yeni sezonun oyunu: Daha hızlı, daha genç, daha cesur",
    dek: "İlk haftaların verisi, önde baskı ve geçiş hücumlarının sezonun ana karakterini belirleyeceğini gösteriyor.",
    publicationSlug: "direktspor",
    categorySlug: "spor",
    author: "Can Doğan",
    publishedAt: "2026-08-25T18:40:00+03:00",
    displayDate: "25 Ağustos 2026",
    readTime: "4 dk",
    premium: false,
    featured: true,
    heroImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Işıklar altında futbol stadyumu",
    photoCredit: "Nathan Rogers / Unsplash",
    body: [
      "Takımlar yalnızca kadrolarını değil, oyunun temposunu da yeniledi. Genç oyuncu tercihi artık geleceğe yatırım cümlesinden çıkıp bugünün fiziksel ihtiyacına verilen doğrudan bir cevaba dönüşüyor.",
      "Topa sahip olma oranı tek başına üstünlüğü açıklamıyor. Asıl fark, top kaybından sonraki beş saniyede ortaya çıkıyor; güçlü başlayan ekipler bu bölümde hem daha kalabalık hem daha kararlı.",
      "Beklerin iç koridora girmesi ve kanatların çizgide kalması, merkezde pas açısını artırıyor. Ancak bu tercih, kayıp sonrası savunmada stoperleri geniş alanla baş başa bırakabiliyor.",
      "Sezonun ilk kırılma noktası, yüksek tempoyu 90 dakikaya yayabilenlerle doğru anda yavaşlayabilenleri ayıracak. Cesaret kadar ritim kontrolü de puan tablosuna yansıyacak.",
    ],
    relatedNewsletterSlug: "ilk-duduk",
    tags: ["Futbol", "Taktik", "Süper Lig"],
  },
  {
    slug: "okula-donus-haftasi-icin-bes-aksamlik-aile-sofrasi",
    title: "Okula dönüş haftası için beş akşamlık aile sofrası",
    dek: "Hazırlaması kolay, mevsime uygun beş akşam yemeği; tek alışveriş listesi ve kısa bir pazar hazırlığıyla.",
    publicationSlug: "kidsgourmet",
    categorySlug: "aile-cocuk",
    author: "Ece Aksoy",
    publishedAt: "2026-08-24T10:00:00+03:00",
    displayDate: "24 Ağustos 2026",
    readTime: "5 dk",
    premium: true,
    featured: true,
    heroImage: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Renkli ve sağlıklı aile sofrası",
    photoCredit: "Anna Pelzer / Unsplash",
    body: [
      "Yeni düzene alışılan ilk hafta için planın ana fikri aynı malzemeyi farklı günlerde değerlendirmek. Böylece hem mutfakta geçirilen süre kısalıyor hem de çocuklar tanıdık tatlarla yeni tabaklara daha kolay yaklaşıyor.",
      "Pazar günü fırınlanan bir tepsi sebzenin yarısı pazartesi makarnaya, kalanı çarşamba günü yoğurtlu bir kaseye dönüşüyor. Haşlanan nohut ise iki ayrı ana öğünün temelini oluşturuyor.",
      "Salı akşamı tavuklu bulgur pilavı, perşembe günü nohut köfteli dürüm, cuma günü ise buzdolabında kalan malzemelerle renkli bir frittata öneriyoruz.",
      "Plan esnek: Her ana yemeğin etsiz alternatifi ve beslenme çantasına ayrılabilecek bir bileşeni var. Amaç kusursuz sofra değil, haftanın karar yükünü azaltmak.",
    ],
    relatedNewsletterSlug: "haftalik-cocuk-menusu",
    tags: ["Aile sofrası", "Haftalık plan", "Çocuk beslenmesi"],
  },
  {
    slug: "evin-yeni-ritmi-daha-az-esya-daha-guclu-atmosfer",
    title: "Evin yeni ritmi: Daha az eşya, daha güçlü atmosfer",
    dek: "Gösterişli objelerin yerini dokusu güçlü yüzeyler, esnek yaşam alanları ve kişisel renk seçimleri alıyor.",
    publicationSlug: "home-trendsetter",
    categorySlug: "ev-tasarim",
    author: "Selin Boran",
    publishedAt: "2026-08-23T11:30:00+03:00",
    displayDate: "23 Ağustos 2026",
    readTime: "7 dk",
    premium: true,
    heroImage: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Doğal dokularla tasarlanmış modern salon",
    photoCredit: "Huy Nguyen / Unsplash",
    body: [
      "Yeni yaklaşım minimalizmden çok editoryal bir seçiciliği işaret ediyor. Mekânlar boşalmıyor; yalnızca her parçanın neden orada olduğu daha görünür hâle geliyor.",
      "Tek bir güçlü yüzey, çok sayıda küçük dekoratif karardan daha etkili. Kireç boya, masif ahşap ve dokulu tekstil bu nedenle aynı mekânda sakin ama katmanlı bir dil kuruyor.",
      "Modüler mobilya küçük evlerin zorunluluğu olmaktan çıktı. Çalışma, dinlenme ve misafir ağırlama hâlleri arasında hızla dönüşen parçalar geniş alanlarda da tercih ediliyor.",
      "Renk paletinde hazır reçeteler geride kalıyor. Toprak tonlarına elektrik mavisi ya da koyu vişne gibi kişisel bir vurgu eklemek, evi katalog görüntüsünden uzaklaştırıyor.",
    ],
    relatedNewsletterSlug: "evde-gundem",
    tags: ["İç mimari", "Trend", "Dekorasyon"],
  },
  {
    slug: "tek-pazar-hazirligi-ile-hafta-boyu-israfi-azaltmak",
    title: "Tek pazar hazırlığıyla hafta boyu israfı azaltmak",
    dek: "Dört temel hazırlık, beş farklı tabak ve çöpe gitmeyen bir buzdolabı için uygulanabilir mutfak planı.",
    publicationSlug: "tariften",
    categorySlug: "gastronomi",
    author: "Mina Aral",
    publishedAt: "2026-08-22T16:30:00+03:00",
    displayDate: "22 Ağustos 2026",
    readTime: "5 dk",
    premium: false,
    heroImage: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Haftalık yemek hazırlığı için renkli sebzeler",
    photoCredit: "Ella Olsson / Unsplash",
    body: [
      "Meal prep fikrini bütün haftayı kutulara doldurmak yerine, birbiriyle konuşan dört temel hazırlık olarak ele aldık: Tahıl, fırın sebze, sos ve pişmiş bakliyat.",
      "Bu dört bileşen pazartesi sıcak kase, salı dürüm, çarşamba salata, perşembe çorba ve cuma fırın yemeği olarak yeniden kurulabiliyor.",
      "Sosları ayrı saklamak dokuyu koruyor. Yeşillikleri yıkayıp tamamen kurutmak, kök sebzeleri ise önceden pişirmek kullanım ömrünü uzatıyor.",
      "En önemli adım alışverişten önce buzdolabındaki açık paketleri listelemek. Planı eldeki malzemenin çevresinde kurmak, israfı azaltan asıl davranış değişikliği.",
    ],
    relatedNewsletterSlug: "aksam-ne-pisirsem",
    tags: ["Mutfak planı", "İsraf", "Tarif"],
  },
  {
    slug: "uyku-borcu-hafta-sonu-kapatilabilir-mi",
    title: "Uyku borcu hafta sonu kapatılabilir mi?",
    dek: "Geç yatılan beş gecenin karşılığını iki uzun sabahla vermek neden sandığımız kadar basit değil?",
    publicationSlug: "rejimde",
    categorySlug: "iyi-yasam",
    author: "Dr. İpek Ulu",
    publishedAt: "2026-08-21T07:30:00+03:00",
    displayDate: "21 Ağustos 2026",
    readTime: "6 dk",
    premium: true,
    heroImage: "https://images.unsplash.com/photo-1455642305367-68834a1da7ab?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Sabah ışığında sade bir yatak odası",
    photoCredit: "Tracey Hocking / Unsplash",
    body: [
      "Hafta sonu daha uzun uyumak kısa süreli yorgunluk hissini azaltabilir; ancak düzensiz saatler biyolojik ritmi ileri kaydırarak pazartesi sabahını daha da zorlaştırabilir.",
      "Uyku borcu yalnızca toplam saat açığı değildir. Derin uyku ile REM evrelerinin düzeni ve her gün benzer saatte alınan gün ışığı da toparlanmanın parçasıdır.",
      "En uygulanabilir yaklaşım hafta sonu kalkış saatini en fazla bir saat geciktirmek, ihtiyaç varsa öğleden önce 20–30 dakikalık kısa uyku eklemektir.",
      "Kalıcı çözüm ise hafta içi yatış saatini bir gecede değil, üçer gün boyunca 15 dakika erkene çekmek. Küçük değişim biyolojik saat tarafından daha kolay kabul edilir.",
    ],
    relatedNewsletterSlug: "iyi-yasam-notlari",
    tags: ["Uyku", "Sağlık", "Rutin"],
  },
  {
    slug: "mikro-trendlerin-omru-neden-kisaliyor",
    title: "Mikro trendlerin ömrü neden giderek kısalıyor?",
    dek: "Bir estetiğin adını öğrendiğimiz anda eskimesi, kültürün değil dağıtım sisteminin hızıyla ilgili olabilir.",
    publicationSlug: "hipinup",
    categorySlug: "kultur-trend",
    author: "Bora Sezer",
    publishedAt: "2026-08-20T14:00:00+03:00",
    displayDate: "20 Ağustos 2026",
    readTime: "5 dk",
    premium: false,
    heroImage: "https://images.unsplash.com/photo-1488841714725-bb4c32d1ac94?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Renkli neon ışıklarla şehir gecesi",
    photoCredit: "Max Bender / Unsplash",
    body: [
      "Bir mikro trend doğduğu topluluğun dışına çıkarken anlamını sadeleştiriyor. Algoritma, kolay tanınan görsel kodları öne taşıdığı için fikir hızla bir alışveriş listesine dönüşüyor.",
      "Adlandırma bu süreci hızlandırıyor. Bir estetik etiket kazandığında aranabilir, üretilebilir ve taklit edilebilir hâle geliyor; ancak aynı anda keşif duygusunu kaybediyor.",
      "Markalar için asıl fırsat trendin yüzeyini kopyalamak değil, hangi davranış ihtiyacından doğduğunu anlamak. Görsel kod değişse de alttaki ihtiyaç daha uzun yaşayabiliyor.",
      "Kısacası trendler bitmiyor; paketleri daha hızlı değişiyor. Kültürel okuryazarlık, yeni paketten önce aynı ihtiyacı görebilmekte yatıyor.",
    ],
    relatedNewsletterSlug: "trend-alarmi",
    tags: ["İnternet kültürü", "Trend", "Marka"],
  },
  {
    slug: "sonbahar-fuar-takvimi-sektorlerin-bulusma-noktalari",
    title: "Sonbahar fuar takvimi: Sektörlerin buluşma noktaları",
    dek: "Eylülden kasıma İstanbul, İzmir ve Antalya’daki öne çıkan profesyonel buluşmalar.",
    publicationSlug: "sektorel-ajanda",
    categorySlug: "is-etkinlik",
    author: "Aslı Ekinci",
    publishedAt: "2026-08-19T09:00:00+03:00",
    displayDate: "19 Ağustos 2026",
    readTime: "4 dk",
    premium: false,
    heroImage: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Kalabalık profesyonel konferans salonu",
    photoCredit: "Samuel Pereira / Unsplash",
    body: [
      "Sonbahar takvimi özellikle gıda, yapı ve turizm sektörlerinde yoğunlaşıyor. Aynı hafta içindeki paralel etkinlikler seyahat planını erken yapmayı gerektiriyor.",
      "İstanbul’da eylülün ikinci yarısı teknoloji ve perakendeye, ekim başı ise yapı malzemelerine ayrılmış durumda. İzmir tarım teknolojilerini, Antalya turizm profesyonellerini ağırlayacak.",
      "Ziyaretçi kaydı kadar ikili görüşme sistemlerine başvuru tarihleri de önemli. Birçok organizasyonda randevu takvimi etkinlikten iki hafta önce kapanıyor.",
      "Takvimdeki her etkinliği sektör, şehir ve son başvuru bilgisiyle ayrı kartlarda derledik; ajandanıza ekleyebileceğiniz bağlantıları bültenimizde bulabilirsiniz.",
    ],
    relatedNewsletterSlug: "haftanin-etkinlikleri",
    tags: ["Fuar", "Etkinlik", "İş dünyası"],
  },
  {
    slug: "halka-arzlarda-yeni-donem-secilen-sirket-ne-anlatiyor",
    title: "Halka arzlarda yeni dönem: Seçilen şirket ne anlatıyor?",
    dek: "Yatırımcı iştahı sürüyor fakat fiyatlama, nakit akışı ve kullanım alanı artık daha sert biçimde ayrışıyor.",
    publicationSlug: "piyasavizyon",
    categorySlug: "ekonomi",
    author: "Deniz Ertem",
    publishedAt: "2026-08-18T17:30:00+03:00",
    displayDate: "18 Ağustos 2026",
    readTime: "7 dk",
    premium: true,
    heroImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Finansal piyasa grafikleri",
    photoCredit: "Maxim Hopman / Unsplash",
    body: [
      "Yeni dönemde yalnızca iskontoya bakmak yeterli değil. Arz gelirinin nerede kullanılacağı, şirketin borç çevirme ihtiyacı ve ana ortağın satış oranı birlikte okunmalı.",
      "Operasyonel nakit üretemeyen şirketlerde büyüme hikâyesi yeni kaynak ihtiyacını erteleyebilir ama ortadan kaldırmaz. Bu yüzden prospektif çarpan kadar nakit dönüşümü de önemli.",
      "Sektör benzerleriyle karşılaştırma yapılırken ölçek ve marj farkı gözden kaçabiliyor. Yüzeyde ucuz görünen şirket, daha düşük kalite nedeniyle haklı bir iskonto taşıyabilir.",
      "Halka arzı kısa vadeli dağıtım sonucu yerine ortaklık kararı gibi ele almak, bilgi setini değiştiriyor. Sorulması gereken ilk soru kaç lot geleceği değil, bu işin nasıl para kazandığı.",
    ],
    relatedNewsletterSlug: "halka-arz-radari",
    tags: ["Halka arz", "Şirket", "Yatırım"],
  },
  {
    slug: "transfer-pazarinda-deger-kimin-oyuncusu-yukseliyor",
    title: "Transfer pazarında değer: Kimin oyuncusu yükseliyor?",
    dek: "Yaş, süre ve çok yönlülük; yeni transfer ekonomisinde isimden daha belirleyici hâle geliyor.",
    publicationSlug: "direktspor",
    categorySlug: "spor",
    author: "Can Doğan",
    publishedAt: "2026-08-17T18:00:00+03:00",
    displayDate: "17 Ağustos 2026",
    readTime: "6 dk",
    premium: true,
    heroImage: "https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=1600&q=82",
    heroAlt: "Futbol sahasında maç anı",
    photoCredit: "Vienna Reyes / Unsplash",
    body: [
      "Kulüpler artık yalnızca bugünkü performansı değil, sözleşme sonunda oluşabilecek ikinci satış değerini de satın alıyor. Bu nedenle 21–24 yaş aralığı fiyatlamada ayrı bir prim taşıyor.",
      "Birden fazla rolde oynayabilmek kadro maliyetini dolaylı biçimde düşürüyor. Hem kanat hem bek oynayan bir futbolcu, teknik direktöre iki farklı maç planı sağlıyor.",
      "Dakika başına aksiyon verisi potansiyeli gösterebilir ancak bağlamdan bağımsız okunamaz. Düşük blokta oynayan takımın stoperiyle önde baskı yapan takımın stoperi aynı metrikle değerlendirilemez.",
      "Yeni transfer piyasasında doğru soru oyuncunun ne kadar tanındığı değil, hangi oyunda değerinin artacağı. Kulübün sistemi, bonservis kadar önemli bir yatırım bileşeni.",
    ],
    relatedNewsletterSlug: "transfer-hatti",
    tags: ["Transfer", "Futbol ekonomisi", "Veri"],
  },
];

export const newsletterBundles: NewsletterBundle[] = [
  {
    slug: "gune-basla",
    name: "Güne Başla",
    eyebrow: "3 bülten · hafta içi",
    description: "Ekonomi, spor ve trend gündemini kahveden önce tek akışta yakala.",
    newsletterSlugs: ["piyasa-acilisi", "ilk-duduk", "trend-alarmi"],
    accent: "#ffd72e",
    featured: true,
  },
  {
    slug: "iyi-yasam-paketi",
    name: "İyi Yaşam",
    eyebrow: "4 bülten · haftalık",
    description: "Aile, sofra, sağlık ve ev için dengeli bir haftalık okuma planı.",
    newsletterSlugs: [
      "haftalik-cocuk-menusu",
      "aksam-ne-pisirsem",
      "iyi-yasam-notlari",
      "evde-gundem",
    ],
    accent: "#9edfc9",
  },
  {
    slug: "profesyonel-radar",
    name: "Profesyonel Radar",
    eyebrow: "3 bülten · iş günü",
    description: "Piyasa sinyalleri, şirketler ve etkinlik takvimi aynı pakette.",
    newsletterSlugs: ["piyasa-acilisi", "halka-arz-radari", "haftanin-etkinlikleri"],
    accent: "#8dcef7",
  },
  {
    slug: "hiposta-dergi",
    name: "Hiposta Dergi",
    eyebrow: "Editör seçkisi · pazar",
    description: "17 yayından haftanın en iyi fikirleri, tek premium sayı.",
    newsletterSlugs: ["hiposta-haftalik"],
    accent: "#b9b7ff",
  },
];
